/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eduvault.view;

import eduvault.dao.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author PC01-107
 */
public class Registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro.class.getName());

    private UsuarioDAO usuarioDAO;
    
    public Registro() {
        usuarioDAO = new UsuarioDAO();
        initComponents();
        setLocationRelativeTo(null);
    }
     private void registrarUsuario() {
        String nombre = txtNombre.getText().trim();
        String correo = txtCorreo.getText().trim();
        String contrasena = new String(txtContrasena.getPassword());
        String confirmar = new String(txtConfirmar.getPassword());
        String carrera = txtCarrera.getText().trim();
        int semestre = (int) cbSemestre.getSelectedItem();
        
        // Validaciones
        if (nombre.isEmpty() || correo.isEmpty() || contrasena.isEmpty() || carrera.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Todos los campos son obligatorios", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!contrasena.equals(confirmar)) {
            JOptionPane.showMessageDialog(this, "⚠️ Las contraseñas no coinciden", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (contrasena.length() < 6) {
            JOptionPane.showMessageDialog(this, "⚠️ La contraseña debe tener al menos 6 caracteres", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Verificar si el correo ya existe
        if (usuarioDAO.existeCorreo(correo)) {
            JOptionPane.showMessageDialog(this, "⚠️ Este correo ya está registrado", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Crear usuario
        Usuario usuario = new Usuario();
        usuario.setNombre(nombre);
        usuario.setCorreo(correo);
        usuario.setContrasena(contrasena);
        usuario.setCarrera(carrera);
        usuario.setSemestre(semestre);
        
        if (usuarioDAO.registrar(usuario)) {
            JOptionPane.showMessageDialog(this, "✅ ¡Registro exitoso! Ahora inicia sesión", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            new Login().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "❌ Error al registrar. Intenta nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 260, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
